- docker-compose.dev.yml
This PR adds the dev docker-compose file, used by the [user-office-develop](https://github.com/UserOfficeProject/user-office-develop)
https://jira.esss.lu.se/browse/SWAP-1163
- dev docker-compose file added
> Swap 1163 update dev env

- Dockerfile
- docker-compose.dev.yml
- package.json
- src/__tests__/payloads.json
- src/__tests__/proposal-pdf.spec.ts
- src/__tests__/sample-pdf.spec.ts
- src/app.ts
- src/pdf/index.ts
- src/template/index.ts
- src/types.ts
- src/util/fileSystem.ts
- src/workflows/index.ts
- src/workflows/proposal.ts
- src/workflows/sample.ts
- templates/sample.hbs
This PR adds support for sample PDF and fixes some bugs.
Samples are supported as standalone PDF and as part of proposals.
Unit tests were added/updated.
https://jira.esss.lu.se/browse/SWAP-1187
- Sample PDF support added 
- Samples added to proposal PDF
- Tests updated
- Bug fixes
> SWAP-1187 add support for sample pdf

- .dockerignore
- .github/workflows/build-push.yml
- .github/workflows/test-build.yml
- Dockerfile
- docker-compose.e2e.yml
- package-lock.json
- package.json
- src/pdf/index.ts
This PR updates the Github action and Docker configurations to improve the overall speed, size of the images and makes action files consistent.
The previous solution didn't use any caching and the generated image was large.
https://jira.esss.lu.se/browse/SWAP-1201
- save intermediate layers after each build and use them if there were no changes
- docker ignore updated to provide a better caching experience 
- use multi-stage builds and alpine to reduce image size (~1gb->~480mb)
- package.json updated to use only proper dependencies in each environment
- e2e test related configurations
https://github.com/UserOfficeProject/user-office-factory/pull/6
> SWAP-1201 CI/CD Improvements

- src/app.ts
- src/pdf/index.ts
This small PR fixes the PDF generation speed (~2s -> ~200ms depending on your PC spec).
Speed up the PDF generation.
https://jira.esss.lu.se/browse/SWAP-1215
- use the correct configuration in the puppeteer
- skip health-checks and static access from HTTP logs
> Factory speedup

- Dockerfile
Hotfix: alpine image version fixed
> Hotfix: alpine image version fixed

- src/__tests__/api/pdf/proposal-pdf.spec.ts
- src/__tests__/api/pdf/sample-pdf.spec.ts
- src/__tests__/fixtures/pdf-payloads.json
- src/template/helpers/common.ts
- src/workflows/pdf/proposal.ts
- templates/partials/questionaryAnswer.hbs
- templates/sample.hbs
This PR aims to fix some sample related issues in PDF download.
There was a big refactor related to sub-templates/samples which introduced some breaking changes in the PDF templates.
https://jira.esss.lu.se/browse/SWAP-1281
https://jira.esss.lu.se/browse/SWAP-1274
- fixed [object Object]
- templates updated
- tests updated
- samples ToC added
https://github.com/UserOfficeProject/user-office-backend/pull/109
> SWAP-1281 SWAP-1274 PDF fixes

- templates/partials/questionaryAnswer.hbs
> Add support for number_input

- src/__tests__/api/pdf/proposal-pdf.spec.ts
- src/__tests__/fixtures/pdf-payloads.json
- src/app.ts
- templates/partials/questionaryAnswer.hbs
This PR adds support to render the new "Rich Text Input" questionary component.
https://jira.esss.lu.se/browse/SWAP-1333
- template updated to render the new component
- embellishment rendering fixed
- unit tests added for the new component and number component
- handle favicon requests
https://github.com/UserOfficeProject/user-office-frontend/pull/223
https://github.com/UserOfficeProject/user-office-backend/pull/155
> SWAP-1333 As a user I want to be able to use subscript

- src/__tests__/api/pdf/proposal-pdf.spec.ts
- src/__tests__/fixtures/pdf-payloads.json
- src/dataSources/FileDataSource.ts
- src/dataSources/postgres/FileDataSource.ts
- src/pdf/index.ts
- src/queries/FileQueries.ts
- src/template/helpers/common.ts
- src/template/helpers/index.ts
- src/template/helpers/questionary.ts
- src/types.ts
- src/workflows/pdf/proposal.ts
- src/workflows/pdf/sample.ts
- templates/partials/questionaryAnswer.hbs
- templates/questionary-step.hbs
- templates/sample.hbs
This PR adds support for inline images with figures and captions.
https://jira.esss.lu.se/browse/SWAP-1363
- images added to attachments
- figure and caption support
https://github.com/UserOfficeProject/user-office-backend/pull/169
https://github.com/UserOfficeProject/user-office-frontend/pull/231
> SWAP-1362 image captions

- src/template/helpers/questionary.ts
This PR fixes the error message display for unsupported filetypes. 
To make it more user-friendly.
- error message changed
> Attachment error message fixed

- .github/workflows/build-push-win.yml
- Dockerfile.dev.win
- Dockerfile.win
Please see here for relevant detail: https://github.com/UserOfficeProject/user-office-backend/pull/303
> 120 win images built in gh actions

- .github/workflows/build-push.yml
Closes: UserOfficeProject/stfc-user-office-project#142
- Created [Jenkins Job](https://ci.devs.facilities.rl.ac.uk/job/Dev_Deploy_ProposalFactory.LatestImage/) to trigger which triggers the kubernetes rollout for the factory.
- Jenkins Job triggers when push to `master` or `develop` branch on the GitHub repo `user-office-factory` happens
- After Jenkins job was created, manually triggered and made sure it was successful.
- Then triggered the job remotely with a curl command on GitBash
- Added the command to `build-push.yml` file, created a branch and pushed to the branch to ensure the Jenkins Job was successfully triggered.
Image above shows GitHub actions has taken place after push was made.
Build was triggered successfully on Jenkins
Command on job has been executed
Fixes: …
> 142 trigger deployment factory

- Dockerfile
- package-lock.json
- package.json
- src/__tests__/api/pdf/proposal-pdf.spec.ts
- src/__tests__/api/pdf/shipment-label-pdf.spec.ts
- src/__tests__/fixtures/pdf-payloads.json
- src/types.ts
- src/workflows/pdf/shipment.ts
- templates/shipment-label.hbs
Closes SWAP-2085
Creating shipment label
Shipment label is used by end user and information on it is consumed by EAM and logistics
https://jira.esss.lu.se/browse/SWAP-2085
Updated shipment label template
Add more data to label
https://github.com/UserOfficeProject/user-office-frontend/pull/701
https://github.com/UserOfficeProject/user-office-backend/pull/521
> feat(label): Adding shipment label

- .github/workflows/lint.yml
- .prettierignore
- src/__tests__/fixtures/pdf-payloads.json
Part of: UserOfficeProject/stfc-user-office-project/issues/234
Adding linter to PRs to maintain consistency and stop any issues not spotted locally
Tested on this PR branch 
Closes: UserOfficeProject/stfc-user-office-project/issues/234 
Added linter .yml file that runs on pull request and gives prettier and eslint errors
> feat: add linter workflow for github actions

- .github/workflows/build-push.yml
This PR aims to make workflows more simple, by using two new custom actions
https://github.com/swapActions/get-branch-name 
https://github.com/swapActions/trigger-useroffice-deployment
This PR also updates old actions to address the warnings for deprecations
> Updating workflows

- templates/partials/questionaryAnswer.hbs
Added dynamic multiple choice data type into PDF generation
https://jira.esss.lu.se/secure/RapidBoard.jspa?rapidView=798&projectKey=SWAP&view=detail&selectedIssue=SWAP-3047
* manual
templates/partials/questionaryAnswer.hbs
> feat: added dynamic multiple choice questionary

- .github/dependabot.yml
Fixing the dependabot package-ecosystem
> fix: fix dependabot.yml package-ecosystem

- .github/workflows/build-push.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/github-tag-and-release.yml
- .github/workflows/lint.yml
- .github/workflows/test-build.yml
- Dockerfile
Our pipelines were using some older actions version and this PR aims to upgrade to latest.
> chore: upgrade chromium version and all the actions in the pipelines

- .github/workflows/build-push.yml
- .github/workflows/test-build.yml
> chore: try to improve builds for arm64 platforms

- Dockerfile
upgrade alpine chromium to latest version. - 114.0.5735.198-r0
To fix build error in Github Action. 
manually
> chore: upgrade alpine chromium to latest version.

- Dockerfile
- Dockerfile.dev
The current version of chromium version doesn't match the prod version.
Upgrade dev chromium to 114.0.5735.198-r0 which matches the prod version.
Closes https://github.com/UserOfficeProject/user-office-factory/issues/237
Manual test.
> Upgrade chromium in  dev to match prod version

- example.custom-proposal-dummy-data.json
Added dummy json for the Custom Proposal template.
> Added example dummy json for the custom proposal.

- package-lock.json
- package.json
This is for release tomorrow 28-11-2023
> Release 27 11 2023

- package-lock.json
- package.json
Reverts UserOfficeProject/user-office-factory#395
> Revert "chore(deps-dev): bump prettier from 3.2.4 to 3.2.5"

- .github/workflows/build-push.yml
- package-lock.json
- package.json
> Staging release 2024 09 23

- LICENSE
Closes: https://github.com/UserOfficeProject/issue-tracker/issues/1166 (user-office-factory)
This is intended for STFC legal and aligns with the Memorandum of Understanding between the contributing parties.
Update licence content
- LICENSE
> feat: update user-office-factory BSD-3 clause licence #1166

- .eslintrc
- package-lock.json
- package.json
- src/__tests__/api/pdf/proposal-zip.spec.ts
- src/config/index.ts
- src/workflows/pdf/PdfEmitter.ts
- src/workflows/pdf/PdfFactory.ts
Closes: https://github.com/UserOfficeProject/issue-tracker/issues/1420
This pull request addresses a backlog of failing dependency updates identified and managed by dependabot. For some time, various dependency update PRs from dependabot have been in a failing state, preventing us from keeping our project dependencies up-to-date.
- Upgrading several dependencies: (`@typescript-eslint/eslint-plugin`,`@typescript-eslint/parser`,`eslint-plugin-unused-imports`,`puppeteer`)
> fix: update packages
